#UN RA / group 4
class Shrub :
    def __init__(self, name, species, height, width, color, climate, average_lifespan, essential_tool):
        self.name = name
        self.species = species
        self.height = height
        self.width = width
        self.color = color
        self.climate = climate
        self.average_lifespan = average_lifespan
        self.essential_tool = essential_tool
        

    def display_info(self):
        info = [
            f"Name : {self.name}",
            f"Species : {self.species}",
            f"Height : {self.height}",
            f"Width : {self.width}",
            f"Color : {self.color}",
            f"Climate : {self.climate}",
            f"Average Lifespan : {self.average_lifespan}",
            f"Essential Tool : {self.essential_tool}"
       ]
        
    print("\n".join(info))

shrubs = [
    Shrub("Abelia", "Abelia", "1.5m - 2m", "1m - 1.5m", "Green", "Temperate", 10, "Pruner"),
    Shrub("Acer", "Maple", "2m - 4m", "1.5m - 3m", "Red, Green", "Temperate", 20, "Shears"),
    Shrub("Actinidia", "Actinidia", "3m - 5m", "2m - 3m", "Green", "Temperate", 15, "Pruner"),
    Shrub("Aloe", "Aloe", "0.5m - 1m", "0.3m - 0.8m", "Green", "Arid", 5, "Spade"),
    Shrub("Aralia", "Angelica Tree", "2m - 3m", "1.5m - 2m", "Green", "Temperate", 25, "Shears, Pruner"),
    Shrub("Arctostaphylos", "Bearberry", "0.2m - 1m", "0.5m - 2m", "Red, Green", "Arid, Temperate", 7, "Hoe"),
    Shrub("Aronia", "Chokeberry", "1.5m - 2m", "1m - 1.5m", "Purple, Red, Green", "Cold, Temperate", 15, "Hoe, Pruner"),
    Shrub("Artemisia", "Sagebrush", "0.5m - 1.5m", "0.5m - 1.2m", "Silver, Green", "Arid, Temperate", 10, "Pruner, Shears"),
    Shrub("Aucuba", "Aucuba", "1m - 2.5m", "0.5m - 1.5m", "Green, Yellow", "Temperate", 20, "Rake, Pruner"),
    Shrub("Berberis", "Barberry", "0.5m - 2m", "0.5m - 1.5m", "Red, Green, Purple", "Temperate", 12, "Shears, Pruner"),
    Shrub("Bougainvillea", "Bougainvillea", "2m - 4m", "2m - 3m", "Purple, Pink, Red, White", "Tropical, Subtropical", 20, "Pruner, Shears"),
    Shrub("Brugmansia", "Angel's trumpet", "3m - 5m", "2.5m - 4m", "White, Yellow, Pink", "Tropical", 10, "Shears, Pruner"),
    Shrub("Buddleja", "Butterfly bush", "1.5m - 3m", "1.2m - 2m", "Purple, White, Pink", "Temperate", 15, "Pruner, Shears"),
    Shrub("Buxus", "Box", "0.5m - 1.5m", "0.5m - 1.2m", "Green", "Temperate", 12, "Rake, Shears"),
    Shrub("Calia", "Mescalbean", "?m - ?m", "?m - ?m", "Red", "Temperate", 15, "Hoe, Pruner"),
    Shrub("Callicarpa", "Beautyberry", "?m - ?m", "?m - ?m", "Purple", "Temperate", 10, "Pruner, Shears"),
    Shrub("Callistemon", "Bottlebrush", "?m - ?m", "?m - ?m", "Red", "Temperate", 8, "Pruner"),
    Shrub("Calluna", "Heather", "?m - ?m", "?m - ?m", "Purple", "Temperate", 20, "Shears"),
    Shrub("Calycanthus", "Sweetshrub", "?m - ?m", "?m - ?m", "Red", "Temperate", 15, "Shears, Pruner"),
    Shrub("Camellia", "Camellia", "?m - ?m", "?m - ?m", "Red, Pink, White", "Temperate", 50, "Shears"),
    Shrub("Caragana", "Pea-tree", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 20, "Pruner"),
    Shrub("Carpenteria", "Carpenteria", "?m - ?m", "?m - ?m", "White", "Temperate", 15, "Shears"),
    Shrub("Caryopteris", "Blue Spiraea", "?m - ?m", "?m - ?m", "Blue", "Temperate", 8, "Pruner"),
    Shrub("Cassiope", "Moss-heather", "?m - ?m", "?m - ?m", "Pink, White", "Temperate", 25, "Shears, Pruner"),
    Shrub("Ceanothus", "Ceanothus", "?m - ?m", "?m - ?m", "Blue", "Temperate", 20, "Pruner"),
    Shrub("Celastrus", "Staff vine", "?m - ?m", "?m - ?m", "Red", "Temperate", 50, "Shears"),
    Shrub("Ceratostigma", "Hardy Plumbago", "?m - ?m", "?m - ?m", "Blue", "Temperate", 10, "Pruner"),
    Shrub("Cercocarpus", "Mountain-mahogany", "?m - ?m", "?m - ?m", "Red, Yellow", "Temperate", 50, "Shears"),
    Shrub("Chaenomeles", "Japanese Quince", "?m - ?m", "?m - ?m", "Red, Pink, White", "Temperate", 25, "Pruner"),
    Shrub("Chamaebatiaria", "Fernbush", "?m - ?m", "?m - ?m", "White", "Temperate", 15, "Shears"),
    Shrub("Chamaedaphne", "Leatherleaf", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 20, "Pruner"),
    Shrub("Chimonanthus", "Wintersweet", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 25, "Shears"),
    Shrub("Chionanthus", "Fringe-tree", "?m - ?m", "?m - ?m", "White", "Temperate", 50, "Pruner"),
    Shrub("Choisya", "Mexican-orange Blossom", "?m - ?m", "?m - ?m", "White", "Temperate", 20, "Shears"),
    Shrub("Cistus", "Rockrose", "?m - ?m", "?m - ?m", "White, Pink", "Arid, Temperate", 10, "Pruner"),
    Shrub("Clerodendrum", "Clerodendrum", "?m - ?m", "?m - ?m", "Red, Purple, White", "Tropical", 15, "Shears"),
    Shrub("Clethra", "Summersweet", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 30, "Pruner"),
    Shrub("Clianthus", "Glory Pea", "?m - ?m", "?m - ?m", "Red", "Temperate", 15, "Shears"),
    Shrub("Colletia", "Colletia", "?m - ?m", "?m - ?m", "White", "Temperate", 25, "Pruner"),
    Shrub("Colutea", "Bladder Senna", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 20, "Shears"),
    Shrub("Comptonia", "Sweetfern", "?m - ?m", "?m - ?m", "Green", "Temperate", 10, "Pruner"),
    Shrub("Cornus", "Dogwood", "?m - ?m", "?m - ?m", "White, Pink, Red", "Temperate", 30, "Shears"),
    Shrub("Corylopsis", "Winter-hazel", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 25, "Pruner"),
    Shrub("Cotinus", "Smoketree", "?m - ?m", "?m - ?m", "Purple", "Temperate", 30, "Shears"),
    Shrub("Cotoneaster", "Cotoneaster", "?m - ?m", "?m - ?m", "Red", "Temperate", 20, "Pruner"),
    Shrub("Cowania", "Cliffrose", "?m - ?m", "?m - ?m", "White", "Temperate", 25, "Shears"),
    Shrub("Crataegus", "Hawthorn", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 30, "Pruner"),
    Shrub("Crinodendron", "Crinodendron", "?m - ?m", "?m - ?m", "Red", "Temperate", 40, "Shears"),
    Shrub("Cytisus", "Broom", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 15, "Pruner"),
    Shrub("Daboecia", "Heath", "?m - ?m", "?m - ?m", "Pink, Purple, White", "Temperate", 20, "Shears"),
    Shrub("Danae", "Alexandrian laurel", "?m - ?m", "?m - ?m", "Green", "Temperate", 25, "Pruner"),
    Shrub("Daphne", "Daphne", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 15, "Shears"),
    Shrub("Decaisnea", "Decaisnea", "?m - ?m", "?m - ?m", "Blue", "Temperate", 30, "Pruner"),
    Shrub("Dasiphora", "Shrubby Cinquefoil", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 15, "Shears"),
    Shrub("Dendromecon", "Tree poppy", "?m - ?m", "?m - ?m", "Yellow", "Arid", 10, "Pruner"),
    Shrub("Desfontainea", "Desfontainea", "?m - ?m", "?m - ?m", "Red, Yellow, Green", "Temperate", 25, "Shears"),
    Shrub("Deutzia", "Deutzia", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 20, "Pruner"),
    Shrub("Chaenomeles", "Japanese Quince", "?m - ?m", "?m - ?m", "Red, Pink, White", "Temperate", 25, "Pruner"),
    Shrub("Chamaebatiaria", "Fernbush", "?m - ?m", "?m - ?m", "White", "Temperate", 15, "Shears"),
    Shrub("Chamaedaphne", "Leatherleaf", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 20, "Pruner"),
    Shrub("Chimonanthus", "Wintersweet", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 25, "Shears"),
    Shrub("Chionanthus", "Fringe-tree", "?m - ?m", "?m - ?m", "White", "Temperate", 50, "Pruner"),
    Shrub("Choisya", "Mexican-orange Blossom", "?m - ?m", "?m - ?m", "White", "Temperate", 20, "Shears"),
    Shrub("Cistus", "Rockrose", "?m - ?m", "?m - ?m", "White, Pink", "Arid, Temperate", 10, "Pruner"),
    Shrub("Clerodendrum", "Clerodendrum", "?m - ?m", "?m - ?m", "Red, Purple, White", "Tropical", 15, "Shears"),
    Shrub("Clethra", "Summersweet", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 30, "Pruner"),
    Shrub("Clianthus", "Glory Pea", "?m - ?m", "?m - ?m", "Red", "Temperate", 15, "Shears"),
    Shrub("Colletia", "Colletia", "?m - ?m", "?m - ?m", "White", "Temperate", 25, "Pruner"),
    Shrub("Colutea", "Bladder Senna", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 20, "Shears"),
    Shrub("Comptonia", "Sweetfern", "?m - ?m", "?m - ?m", "Green", "Temperate", 10, "Pruner"),
    Shrub("Cornus", "Dogwood", "?m - ?m", "?m - ?m", "White, Pink, Red", "Temperate", 30, "Shears"),
    Shrub("Corylopsis", "Winter-hazel", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 25, "Pruner"),
    Shrub("Cotinus", "Smoketree", "?m - ?m", "?m - ?m", "Purple", "Temperate", 30, "Shears"),
    Shrub("Cotoneaster", "Cotoneaster", "?m - ?m", "?m - ?m", "Red", "Temperate", 20, "Pruner"),
    Shrub("Cowania", "Cliffrose", "?m - ?m", "?m - ?m", "White", "Temperate", 25, "Shears"),
    Shrub("Crataegus", "Hawthorn", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 30, "Pruner"),
    Shrub("Crinodendron", "Crinodendron", "?m - ?m", "?m - ?m", "Red", "Temperate", 40, "Shears"),
    Shrub("Cytisus", "Broom", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 15, "Pruner"),
    Shrub("Daboecia", "Heath", "?m - ?m", "?m - ?m", "Pink, Purple, White", "Temperate", 20, "Shears"),
    Shrub("Danae", "Alexandrian laurel", "?m - ?m", "?m - ?m", "Green", "Temperate", 25, "Pruner"),
    Shrub("Daphne", "Daphne", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 15, "Shears"),
    Shrub("Decaisnea", "Decaisnea", "?m - ?m", "?m - ?m", "Blue", "Temperate", 30, "Pruner"),
    Shrub("Dasiphora", "Shrubby Cinquefoil", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 15, "Shears"),
    Shrub("Dendromecon", "Tree poppy", "?m - ?m", "?m - ?m", "Yellow", "Arid", 10, "Pruner"),
    Shrub("Desfontainea", "Desfontainea", "?m - ?m", "?m - ?m", "Red, Yellow, Green", "Temperate", 25, "Shears"),
    Shrub("Deutzia", "Deutzia", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 20, "Pruner"),
    Shrub("Diervilla", "Bush honeysuckle", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 15, "Pruner"),
    Shrub("Dipelta", "Dipelta", "?m - ?m", "?m - ?m", "Pink", "Temperate", 20, "Shears"),
    Shrub("Dirca", "Leatherwood", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 25, "Pruner"),
    Shrub("Dracaena", "Dragon tree", "?m - ?m", "?m - ?m", "Green", "Tropical", 30, "Shears"),
    Shrub("Drimys", "Winter's Bark", "?m - ?m", "?m - ?m", "White", "Temperate", 40, "Pruner"),
    Shrub("Dryas", "Mountain Avens", "?m - ?m", "?m - ?m", "White, Yellow", "Temperate", 15, "Shears"),
    Shrub("Edgeworthia", "Paper Bush", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 20, "Pruner"),
    Shrub("Elaeagnus", "Elaeagnus", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 40, "Shears"),
    Shrub("Embothrium", "Chilean Firebush", "?m - ?m", "?m - ?m", "Red", "Temperate", 50, "Pruner"),
    Shrub("Empetrum", "Crowberry", "?m - ?m", "?m - ?m", "Purple, Black", "Temperate", 30, "Shears"),
    Shrub("Enkianthus", "Pagoda Bush", "?m - ?m", "?m - ?m", "Red", "Temperate", 50, "Pruner"),
    Shrub("Ephedra", "Ephedra", "?m - ?m", "?m - ?m", "Green", "Arid", 20, "Shears"),
    Shrub("Epigaea", "Trailing Arbutus", "?m - ?m", "?m - ?m", "Pink, White", "Temperate", 20, "Pruner"),
    Shrub("Erica", "Heath", "?m - ?m", "?m - ?m", "Pink, Purple, White", "Temperate", 25, "Shears"),
    Shrub("Eriobotrya", "Loquat", "?m - ?m", "?m - ?m", "White", "Tropical", 30, "Pruner"),
    Shrub("Escallonia", "Escallonia", "?m - ?m", "?m - ?m", "Pink, White", "Temperate", 20, "Shears"),
    Shrub("Eucryphia", "Eucryphia", "?m - ?m", "?m - ?m", "White", "Temperate", 50, "Pruner"),
    Shrub("Euonymus", "Spindle", "?m - ?m", "?m - ?m", "Red", "Temperate", 25, "Shears"),
    Shrub("Exochorda", "Pearl Bush", "?m - ?m", "?m - ?m", "White", "Temperate", 20, "Pruner"),
    Shrub("Fabiana", "Fabiana", "?m - ?m", "?m - ?m", "Purple", "Temperate", 30, "Shears"),
    Shrub("Fallugia", "Apache Plume", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 15, "Pruner"),
    Shrub("Fatsia", "Fatsia", "?m - ?m", "?m - ?m", "White", "Temperate", 20, "Shears"),
    Shrub("Forsythia", "Forsythia", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 20, "Pruner"),
    Shrub("Fothergilla", "Fothergilla", "?m - ?m", "?m - ?m", "White", "Temperate", 25, "Shears"),
    Shrub("Franklinia", "Franklinia", "?m - ?m", "?m - ?m", "White", "Temperate", 30, "Pruner"),
    Shrub("Fremontodendron", "Flannelbush", "?m - ?m", "?m - ?m", "Yellow, Orange", "Arid", 25, "Shears"),
    Shrub("Fuchsia", "Fuchsia", "?m - ?m", "?m - ?m", "Purple, Pink, White", "Temperate", 10, "Pruner"),
    Shrub("Garrya", "Silk-tassel", "?m - ?m", "?m - ?m", "Green", "Temperate", 50, "Shears"),
    Shrub("Gaultheria", "Salal", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 20, "Pruner"),
    Shrub("Gaylussacia", "Huckleberry", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 20, "Shears"),
    Shrub("Genista", "Broom", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 15, "Pruner"),
    Shrub("Gordonia", "Loblolly-bay", "?m - ?m", "?m - ?m", "White", "Temperate", 50, "Shears"),
    Shrub("Grevillea", "Grevillea", "?m - ?m", "?m - ?m", "Red, Yellow, Pink", "Tropical", 30, "Pruner"),
    Shrub("Griselinia", "Griselinia", "?m - ?m", "?m - ?m", "Green", "Temperate", 30, "Shears"),
    Shrub("Hakea", "Hakea", "?m - ?m", "?m - ?m", "White", "Temperate", 20, "Pruner"),
    Shrub("Halesia", "Silverbell", "?m - ?m", "?m - ?m", "White", "Temperate", 50, "Shears"),
    Shrub("Halimium", "Rockrose", "?m - ?m", "?m - ?m", "White, Pink, Yellow", "Arid, Temperate", 10, "Pruner"),
    Shrub("Hamamelis", "Witch-hazel", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 30, "Shears"),
    Shrub("Hebe", "Hebe", "?m - ?m", "?m - ?m", "White, Pink, Purple", "Temperate", 20, "Pruner"),
    Shrub("Hedera", "Ivy", "?m - ?m", "?m - ?m", "Green", "Temperate", 50, "Shears"),
    Shrub("Helianthemum", "Rockrose", "?m - ?m", "?m - ?m", "White, Pink, Yellow", "Arid, Temperate", 10, "Pruner"),
    Shrub("Helianthus", "Sunflower", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 15, "Shears"),
    Shrub("Helichrysum", "Curry Plant", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 10, "Pruner"),
    Shrub("Hemerocallis", "Daylily", "?m - ?m", "?m - ?m", "Yellow, Orange", "Temperate", 15, "Shears"),
    Shrub("Heteromeles", "Toyon", "?m - ?m", "?m - ?m", "White", "Temperate", 50, "Pruner"),
    Shrub("Heuchera", "Coral Bells", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 15, "Shears"),
    Shrub("Hibbertia", "Hibbertia", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 15, "Pruner"),
    Shrub("Hibiscus", "Hibiscus", "?m - ?m", "?m - ?m", "Red, Pink, Yellow, White", "Tropical", 15, "Shears"),
    Shrub("Holodiscus", "Ocean-spray", "?m - ?m", "?m - ?m", "White", "Temperate", 30, "Pruner"),
    Shrub("Hoya", "Hoya", "?m - ?m", "?m - ?m", "Pink", "Tropical", 30, "Shears"),
    Shrub("Hudsonia", "Golden Heather", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 10, "Pruner"),
    Shrub("Hydrangea", "Hydrangea", "?m - ?m", "?m - ?m", "Pink, Blue, White", "Temperate", 20, "Shears"),
    Shrub("Hypericum", "St. John's Wort", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 15, "Pruner"),
    Shrub("Ilex", "Holly", "?m - ?m", "?m - ?m", "Red, Green", "Temperate", 50, "Shears"),
    Shrub("Indigofera", "Indigofera", "?m - ?m", "?m - ?m", "Pink", "Temperate", 15, "Pruner"),
    Shrub("Itea", "Sweet Spire", "?m - ?m", "?m - ?m", "White", "Temperate", 20, "Shears"),
    Shrub("Jacaranda", "Jacaranda", "?m - ?m", "?m - ?m", "Purple", "Tropical", 50, "Pruner"),
    Shrub("Jasminum", "Jasmine", "?m - ?m", "?m - ?m", "White, Yellow", "Temperate", 30, "Shears"),
    Shrub("Juniperus", "Juniper", "?m - ?m", "?m - ?m", "Green, Blue", "Temperate", 50, "Pruner"),
    Shrub("Kalmia", "Mountain-laurel", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 40, "Shears"),
    Shrub("Kerria", "Japanese Rose", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 20, "Pruner"),
    Shrub("Knautia", "Knautia", "?m - ?m", "?m - ?m", "Purple", "Temperate", 20, "Shears"),
    Shrub("Kolkwitzia", "Beautybush", "?m - ?m", "?m - ?m", "Pink", "Temperate", 30, "Pruner"),
    Shrub("Laburnum", "Laburnum", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 50, "Shears"),
    Shrub("Lantana", "Lantana", "?m - ?m", "?m - ?m", "Pink, Yellow, Orange", "Tropical", 10, "Pruner"),
    Shrub("Larix", "Larch", "?m - ?m", "?m - ?m", "Green", "Temperate", 50, "Shears"),
    Shrub("Lavandula", "Lavender", "?m - ?m", "?m - ?m", "Purple, White", "Arid, Temperate", 15, "Pruner"),
    Shrub("Leptospermum", "Leptospermum", "?m - ?m", "?m - ?m", "White, Pink, Red", "Temperate", 30, "Shears"),
    Shrub("Lespedeza", "Lespedeza", "?m - ?m", "?m - ?m", "Pink, White", "Temperate", 20, "Pruner"),
    Shrub("Leucothoe", "Leucothoe", "?m - ?m", "?m - ?m", "White", "Temperate", 25, "Shears"),
    Shrub("Leycesteria", "Leycesteria", "?m - ?m", "?m - ?m", "White, Purple", "Temperate", 10, "Pruner"),
    Shrub("Ligustrum", "Privet", "?m - ?m", "?m - ?m", "White", "Temperate", 50, "Shears"),
    Shrub("Lilium", "Lily", "?m - ?m", "?m - ?m", "Yellow, Orange, Pink, White", "Temperate", 10, "Pruner"),
    Shrub("Linnaea", "Twinflower", "?m - ?m", "?m - ?m", "Pink", "Temperate", 15, "Shears"),
    Shrub("Liquidambar", "Sweetgum", "?m - ?m", "?m - ?m", "Green", "Temperate", 50, "Shears"),
    Shrub("Liriodendron", "Tulip tree", "?m - ?m", "?m - ?m", "Yellow, Green", "Temperate", 50, "Pruner"),
    Shrub("Lonicera", "Honeysuckle", "?m - ?m", "?m - ?m", "White, Yellow, Pink", "Temperate", 20, "Shears"),
    Shrub("Magnolia", "Magnolia", "?m - ?m", "?m - ?m", "White, Pink, Purple", "Temperate", 50, "Pruner"),
    Shrub("Malus", "Apple", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 50, "Shears"),
    Shrub("Mespilus", "Medlar", "?m - ?m", "?m - ?m", "White", "Temperate", 50, "Pruner"),
    Shrub("Nandina", "Heavenly Bamboo", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 20, "Shears"),
    Shrub("Nerium", "Oleander", "?m - ?m", "?m - ?m", "Pink, Red, White", "Temperate", 20, "Pruner"),
    Shrub("Oenothera", "Evening Primrose", "?m - ?m", "?m - ?m", "Yellow, Pink", "Temperate", 10, "Shears"),
    Shrub("Osmanthus", "Osmanthus", "?m - ?m", "?m - ?m", "White", "Temperate", 50, "Pruner"),
    Shrub("Paeonia", "Peony", "?m - ?m", "?m - ?m", "White, Pink, Red", "Temperate", 50, "Shears"),
    Shrub("Philadelphus", "Mock-orange", "?m - ?m", "?m - ?m", "White", "Temperate", 50, "Pruner"),
    Shrub("Pieris", "Pieris", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 30, "Shears"),
    Shrub("Plumbago", "Leadwort", "?m - ?m", "?m - ?m", "Blue", "Temperate", 10, "Pruner"),
    Shrub("Polygala", "Polygala", "?m - ?m", "?m - ?m", "Purple", "Temperate", 20, "Shears"),
    Shrub("Potentilla", "Potentilla", "?m - ?m", "?m - ?m", "Yellow, White", "Temperate", 20, "Pruner"),
    Shrub("Prunus", "Cherry", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 50, "Shears"),
    Shrub("Pseudotsuga", "Douglas-fir", "?m - ?m", "?m - ?m", "Green", "Temperate", 50, "Pruner"),
    Shrub("Ptelea", "Hop tree", "?m - ?m", "?m - ?m", "Green", "Temperate", 50, "Shears"),
    Shrub("Punica", "Pomegranate", "?m - ?m", "?m - ?m", "Red", "Temperate", 20, "Pruner"),
    Shrub("Quercus", "Oak", "?m - ?m", "?m - ?m", "Green", "Temperate", 50, "Shears"),
    Shrub("Rhododendron", "Rhododendron", "?m - ?m", "?m - ?m", "Purple, Pink, White", "Temperate", 50, "Pruner"),
    Shrub("Rhus", "Sumac", "?m - ?m", "?m - ?m", "Yellow, Red", "Temperate", 50, "Shears"),
    Shrub("Ribes", "Currant", "?m - ?m", "?m - ?m", "White, Pink, Red, Yellow", "Temperate", 20, "Pruner"),
    Shrub("Robinia", "Black Locust", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 50, "Shears"),
    Shrub("Rosa", "Rose", "?m - ?m", "?m - ?m", "White, Pink, Red, Yellow", "Temperate", 20, "Pruner"),
    Shrub("Rubus", "Blackberry", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 20, "Shears"),
    Shrub("Salix", "Willow", "?m - ?m", "?m - ?m", "Green", "Temperate", 50, "Pruner"),
    Shrub("Sambucus", "Elder", "?m - ?m", "?m - ?m", "White", "Temperate", 20, "Shears"),
    Shrub("Skimmia", "Skimmia", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 30, "Pruner"),
    Shrub("Sorbaria", "False spirea", "?m - ?m", "?m - ?m", "White", "Temperate", 20, "Shears"),
    Shrub("Spartium", "Spanish Broom", "?m - ?m", "?m - ?m", "Yellow", "Temperate", 20, "Pruner"),
    Shrub("Spiraea", "Spiraea", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 20, "Shears"),
    Shrub("Stephanandra", "Stephanandra", "?m - ?m", "?m - ?m", "Green", "Temperate", 30, "Pruner"),
    Shrub("Stewartia", "Stewartia", "?m - ?m", "?m - ?m", "White", "Temperate", 50, "Shears"),
    Shrub("Styrax", "Styrax", "?m - ?m", "?m - ?m", "White", "Temperate", 50, "Pruner"),
    Shrub("Symphoricarpos", "Snowberry", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 20, "Shears"),
    Shrub("Syringa", "Lilac", "?m - ?m", "?m - ?m", "Purple, White, Pink", "Temperate", 20, "Pruner"),
    Shrub("Tamarix", "Tamarix", "?m - ?m", "?m - ?m", "Pink, White", "Arid", 20, "Shears"),
    Shrub("Taxus", "Yew", "?m - ?m", "?m - ?m", "Green", "Temperate", 50, "Pruner"),
    Shrub("Thuja", "Arborvitae", "?m - ?m", "?m - ?m", "Green", "Temperate", 50, "Shears"),
    Shrub("Tibouchina", "Glory Bush", "?m - ?m", "?m - ?m", "Purple, Pink", "Tropical", 20, "Pruner"),
    Shrub("Tilia", "Linden", "?m - ?m", "?m - ?m", "Yellow, White", "Temperate", 50, "Shears"),
    Shrub("Trochodendron", "Wheel Tree", "?m - ?m", "?m - ?m", "Green", "Temperate", 50, "Pruner"),
    Shrub("Tsuga", "Hemlock", "?m - ?m", "?m - ?m", "Green", "Temperate", 50, "Shears"),
    Shrub("Vaccinium", "Blueberry", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 15, "Pruner"),
    Shrub("Viburnum", "Viburnum", "?m - ?m", "?m - ?m", "White, Pink", "Temperate", 30, "Shears"),
    Shrub("Weigela", "Weigela", "?m - ?m", "?m - ?m", "Pink, Red, White", "Temperate", 20, "Pruner"),
    Shrub("Wisteria", "Wisteria", "?m - ?m", "?m - ?m", "Purple, White, Pink", "Temperate", 15, "Shears"),
    Shrub("Yucca", "Yucca", "?m - ?m", "?m - ?m", "White", "Arid", 30, "Pruner"),
    Shrub("Zanthoxylum", "Prickly Ash", "?m - ?m", "?m - ?m", "Green", "Temperate", 20, "Shears"),
    Shrub("Zelkova", "Zelkova", "?m - ?m", "?m - ?m", "Green", "Temperate", 50, "Pruner"),
    Shrub("Ziziphus", "Jujube", "?m - ?m", "?m - ?m", "Yellow, Green", "Tropical", 15, "Shears"),
]