from .ShrubPlant import ShrubPlants

class Shrub(ShrubPlants):
    def __init__(self, name, species, height, width, color, climate, average_lifespan, essential_tool):
        super().__init__(name, species, height, width, color, climate, average_lifespan, essential_tool)


shrubs_data = [
    Shrub("Abelia", "Abelia", "1.5m - 2m", "1m - 1.5m", "Green", "Temperate", 10, "Pruner"),
    Shrub("Acer", "Maple", "2m - 4m", "1.5m - 3m", "Red, Green", "Temperate", 20, "Shears"),
    Shrub("Actinidia", "Actinidia", "3m - 5m", "2m - 3m", "Green", "Temperate", 15, "Pruner"),
    Shrub("Aloe", "Aloe", "0.5m - 1m", "0.3m - 0.8m", "Green", "Arid", 5, "Spade"),
    Shrub("Aralia", "Angelica Tree", "2m - 3m", "1.5m - 2m", "Green", "Temperate", 25, "Shears, Pruner"),
    Shrub("Arctostaphylos", "Bearberry", "0.2m - 1m", "0.5m - 2m", "Red, Green", "Arid, Temperate", 7, "Hoe"),
    Shrub("Aronia", "Chokeberry", "1.5m - 2m", "1m - 1.5m", "Purple, Red, Green", "Cold, Temperate", 15, "Hoe, Pruner"),
    Shrub("Artemisia", "Sagebrush", "0.5m - 1.5m", "0.5m - 1.2m", "Silver, Green", "Arid, Temperate", 10, "Pruner, Shears"),
    Shrub("Aucuba", "Aucuba", "1m - 2.5m", "0.5m - 1.5m", "Green, Yellow", "Temperate", 20, "Rake, Pruner"),
    Shrub("Berberis", "Barberry", "0.5m - 2m", "0.5m - 1.5m", "Red, Green, Purple", "Temperate", 12, "Shears, Pruner"),
    Shrub("Bougainvillea", "Bougainvillea", "2m - 4m", "2m - 3m", "Purple, Pink, Red, White", "Tropical, Subtropical", 20, "Pruner, Shears"),
    Shrub("Brugmansia", "Angel's trumpet", "3m - 5m", "2.5m - 4m", "White, Yellow, Pink", "Tropical", 10, "Shears, Pruner"),
    Shrub("Buddleja", "Butterfly bush", "1.5m - 3m", "1.2m - 2m", "Purple, White, Pink", "Temperate", 15, "Pruner, Shears"),
    Shrub("Buxus", "Box", "0.5m - 1.5m", "0.5m - 1.2m", "Green", "Temperate", 12, "Rake, Shears"),
    Shrub("Calia", "Mescalbean", "1.5m - 3m", "1m - 2m", "Red", "Temperate", 15, "Hoe, Pruner"),
    Shrub("Callicarpa", "Beautyberry", "1m - 3m", "1m - 2m", "Purple", "Temperate", 10, "Pruner, Shears"),
    Shrub("Callistemon", "Bottlebrush", "2m - 4m", "1m - 2m", "Red", "Temperate", 8, "Pruner"),
    Shrub("Calluna", "Heather", "0.1m - 0.6m", "0.3m - 1m", "Purple", "Temperate", 20, "Shears"),
    Shrub("Calycanthus", "Sweetshrub", "1.5m - 3m", "1m - 2m", "Red", "Temperate", 15, "Shears, Pruner"),
    Shrub("Camellia", "Camellia", "1m - 5m", "1m - 2m", "Red, Pink, White", "Temperate", 50, "Shears"),
    Shrub("Caragana", "Pea-tree", "2m - 4m", "1m - 2m", "Yellow", "Temperate", 20, "Pruner"),
    Shrub("Carpenteria", "Carpenteria", "1.5m - 3m", "1m - 2m", "White", "Temperate", 15, "Shears"),
    Shrub("Caryopteris", "Blue Spiraea", "0.5m - 1m", "0.5m - 1m", "Blue", "Temperate", 8, "Pruner"),
    Shrub("Cassiope", "Moss-heather", "0.1m - 0.3m", "0.3m - 0.6m", "Pink, White", "Temperate", 25, "Shears, Pruner"),
    Shrub("Ceanothus", "Ceanothus", "0.5m - 3m", "0.5m - 2m", "Blue", "Temperate", 20, "Pruner"),
    Shrub("Celastrus", "Staff vine", "3m - 10m", "2m - 5m", "Red", "Temperate", 50, "Shears"),
    Shrub("Ceratostigma", "Hardy Plumbago", "0.1m - 0.5m", "0.3m - 1m", "Blue", "Temperate", 10, "Pruner"),
    Shrub("Cercocarpus", "Mountain-mahogany", "2m - 6m", "1m - 3m", "Red, Yellow", "Temperate", 50, "Shears"),
    Shrub("Chaenomeles", "Japanese Quince", "1m - 3m", "1m - 2m", "Red, Pink, White", "Temperate", 25, "Pruner"),
    Shrub("Chamaebatiaria", "Fernbush", "1m - 3m", "1m - 2m", "White", "Temperate", 15, "Shears"),
    Shrub("Chamaedaphne", "Leatherleaf", "1m - 2m", "1m - 2m", "White, Pink", "Temperate", 20, "Pruner"),
    Shrub("Chimonanthus", "Wintersweet", "2m - 4m", "1m - 2m", "Yellow", "Temperate", 25, "Shears"),
    Shrub("Chionanthus", "Fringe-tree", "3m - 10m", "2m - 5m", "White", "Temperate", 50, "Pruner"),
    Shrub("Choisya", "Mexican-orange Blossom", "1m - 3m", "1m - 2m", "White", "Temperate", 20, "Shears"),
    Shrub("Cistus", "Rockrose", "0.1m - 0.5m", "0.3m - 1m", "White, Pink", "Arid, Temperate", 10, "Pruner"),
    Shrub("Clerodendrum", "Clerodendrum", "1m - 3m", "1m - 2m", "Red, Purple, White", "Tropical", 15, "Shears"),
    Shrub("Clethra", "Summersweet", "1m - 2m", "1m - 2m", "White, Pink", "Temperate", 30, "Pruner"),
    Shrub("Clianthus", "Glory Pea", "2m - 4m", "1m - 2m", "Red", "Temperate", 15, "Shears"),
    Shrub("Colletia", "Colletia", "0.5m - 2m", "0.5m - 1.5m", "White", "Temperate", 25, "Pruner"),
    Shrub("Colutea", "Bladder Senna", "1m - 3m", "1m - 2m", "Yellow", "Temperate", 20, "Shears"),
    Shrub("Comptonia", "Sweetfern", "0.5m - 1m", "0.5m - 1m", "Green", "Temperate", 10, "Pruner"),
    Shrub("Cornus", "Dogwood", "1m - 6m", "1m - 3m", "White, Pink, Red", "Temperate", 30, "Shears"),
    Shrub("Corylopsis", "Winter-hazel", "1m - 4m", "1m - 2m", "Yellow", "Temperate", 25, "Pruner"),
    Shrub("Cotinus", "Smoketree", "1m - 6m", "1m - 3m", "Purple", "Temperate", 30, "Shears"),
    Shrub("Cotoneaster", "Cotoneaster", "0.5m - 3m", "0.5m - 2m", "Red", "Temperate", 20, "Pruner"),
    Shrub("Cowania", "Cliffrose", "1m - 3m", "1m - 2m", "White", "Temperate", 25, "Shears"),
    Shrub("Crataegus", "Hawthorn", "1m - 6m", "1m - 3m", "White, Pink", "Temperate", 30, "Pruner"),
    Shrub("Crinodendron", "Crinodendron", "1m - 10m", "1m - 5m", "Red", "Temperate", 40, "Shears"),
    Shrub("Cytisus", "Broom", "0.5m - 3m", "0.5m - 2m", "Yellow", "Temperate", 15, "Pruner"),
    Shrub("Daboecia", "Heath", "0.5m - 2m", "0.5m - 1.5m", "Pink, Purple, White", "Temperate", 20, "Shears"),
    Shrub("Danae", "Alexandrian laurel", "1m - 2m", "0.5m - 1m", "Green", "Temperate", 25, "Pruner"),
    Shrub("Daphne", "Daphne", "0.5m - 1m", "0.5m - 1m", "White, Pink", "Temperate", 15, "Shears"),
    Shrub("Decaisnea", "Decaisnea", "2m - 6m", "1m - 3m", "Blue", "Temperate", 30, "Pruner"),
    Shrub("Dasiphora", "Shrubby Cinquefoil", "0.5m - 2m", "0.5m - 1.5m", "Yellow", "Temperate", 15, "Shears"),
    Shrub("Dendromecon", "Tree poppy", "1m - 3m", "1m - 2m", "Yellow", "Arid", 10, "Pruner"),
    Shrub("Desfontainea", "Desfontainea", "1m - 3m", "1m - 2m", "Red, Yellow, Green", "Temperate", 25, "Shears"),
    Shrub("Deutzia", "Deutzia", "0.5m - 3m", "0.5m - 2m", "White, Pink", "Temperate", 20, "Pruner"),
    Shrub("Diervilla", "Bush honeysuckle", "0.5m - 2m", "0.5m - 1.5m", "Yellow", "Temperate", 15, "Pruner"),
    Shrub("Dipelta", "Dipelta", "1m - 3m", "1m - 2m", "Pink", "Temperate", 20, "Shears"),
    Shrub("Dirca", "Leatherwood", "1m - 2m", "1m - 2m", "Yellow", "Temperate", 25, "Pruner"),
    Shrub("Dracaena", "Dragon tree", "1m - 3m", "0.5m - 1m", "Green", "Tropical", 30, "Shears"),
    Shrub("Drimys", "Winter's Bark", "1m - 6m", "1m - 3m", "White", "Temperate", 40, "Pruner"),
    Shrub("Dryas", "Mountain Avens", "0.1m - 0.5m", "0.3m - 1m", "White, Yellow", "Temperate", 15, "Shears"),
    Shrub("Edgeworthia", "Paper Bush", "1m - 2m", "1m - 2m", "Yellow", "Temperate", 20, "Pruner"),
    Shrub("Elaeagnus", "Elaeagnus", "1m - 3m", "1m - 3m", "Yellow", "Temperate", 40, "Shears"),
    Shrub("Embothrium", "Chilean Firebush", "3m - 5m", "3m - 5m", "Red", "Temperate", 50, "Pruner"),
    Shrub("Empetrum", "Crowberry", "0.5m - 1m", "0.5m - 1m", "Purple, Black", "Temperate", 30, "Shears"),
    Shrub("Enkianthus", "Pagoda Bush", "2m - 4m", "2m - 4m", "Red", "Temperate", 50, "Pruner"),
    Shrub("Ephedra", "Ephedra", "1m - 3m", "1m - 3m", "Green", "Arid", 20, "Shears"),
    Shrub("Epigaea", "Trailing Arbutus", "0.1m - 0.3m", "0.1m - 0.3m", "Pink, White", "Temperate", 20, "Pruner"),
    Shrub("Erica", "Heath", "0.3m - 1m", "0.3m - 1m", "Pink, Purple, White", "Temperate", 25, "Shears"),
    Shrub("Eriobotrya", "Loquat", "3m - 5m", "3m - 5m", "White", "Tropical", 30, "Pruner"),
    Shrub("Escallonia", "Escallonia", "1m - 3m", "1m - 3m", "Pink, White", "Temperate", 20, "Shears"),
    Shrub("Eucryphia", "Eucryphia", "2m - 5m", "2m - 5m", "White", "Temperate", 50, "Pruner"),
    Shrub("Euonymus", "Spindle", "0.5m - 2m", "0.5m - 2m", "Red", "Temperate", 25, "Shears"),
    Shrub("Exochorda", "Pearl Bush", "1m - 3m", "1m - 3m", "White", "Temperate", 20, "Pruner"),
    Shrub("Fabiana", "Fabiana", "1m - 3m", "1m - 3m", "Purple", "Temperate", 30, "Shears"),
    Shrub("Fallugia", "Apache Plume", "0.5m - 2m", "0.5m - 2m", "White, Pink", "Temperate", 15, "Pruner"),
    Shrub("Fatsia", "Fatsia", "1m - 3m", "1m - 3m", "White", "Temperate", 20, "Shears"),
    Shrub("Forsythia", "Forsythia", "1m - 3m", "1m - 3m", "Yellow", "Temperate", 20, "Pruner"),
    Shrub("Fothergilla", "Fothergilla", "1m - 2m", "1m - 2m", "White", "Temperate", 25, "Shears"),
    Shrub("Franklinia", "Franklinia", "2m - 3m", "2m - 3m", "White", "Temperate", 30, "Pruner"),
    Shrub("Fremontodendron", "Flannelbush", "1m - 2m", "1m - 2m", "Yellow, Orange", "Arid", 25, "Shears"),
    Shrub("Fuchsia", "Fuchsia", "0.5m - 1m", "0.5m - 1m", "Purple, Pink, White", "Temperate", 10, "Pruner"),
    Shrub("Garrya", "Silk-tassel", "1m - 3m", "1m - 3m", "Green", "Temperate", 50, "Shears"),
    Shrub("Gaultheria", "Salal", "0.5m - 1m", "0.5m - 1m", "White, Pink", "Temperate", 20, "Pruner"),
    Shrub("Gaylussacia", "Huckleberry", "0.5m - 2m", "0.5m - 2m", "White, Pink", "Temperate", 20, "Shears"),
    Shrub("Genista", "Broom", "1m - 2m", "1m - 2m", "Yellow", "Temperate", 15, "Pruner"),
    Shrub("Gordonia", "Loblolly-bay", "1m - 3m", "1m - 3m", "White", "Temperate", 50, "Shears"),
    Shrub("Grevillea", "Grevillea", "1m - 3m", "1m - 3m", "Red, Yellow, Pink", "Tropical", 30, "Pruner"),
    Shrub("Griselinia", "Griselinia", "1m - 3m", "1m - 3m", "Green", "Temperate", 30, "Shears"),
    Shrub("Hakea", "Hakea", "1m - 3m", "1m - 3m", "White", "Temperate", 20, "Pruner"),
    Shrub("Halesia", "Silverbell", "1m - 3m", "1m - 3m", "White", "Temperate", 50, "Shears"),
    Shrub("Halimium", "Rockrose", "0.5m - 1m", "0.5m - 1m", "White, Pink, Yellow", "Arid, Temperate", 10, "Pruner"),
    Shrub("Hamamelis", "Witch-hazel", "1m - 3m", "1m - 3m", "Yellow", "Temperate", 30, "Shears"),
    Shrub("Hebe", "Hebe", "0.5m - 2m", "0.5m - 2m", "White, Pink, Purple", "Temperate", 20, "Pruner"),
    Shrub("Hedera", "Ivy", "1m - 3m", "1m - 3m", "Green", "Temperate", 50, "Shears"),
    Shrub("Helianthemum", "Rockrose", "0.5m - 1m", "0.5m - 1m", "White, Pink, Yellow", "Arid, Temperate", 10, "Pruner"),
    Shrub("Helianthus", "Sunflower", "1m - 3m", "1m - 3m", "Yellow", "Temperate", 15, "Shears"),
    Shrub("Helichrysum", "Curry Plant", "0.5m - 1m", "0.5m - 1m", "Yellow", "Temperate", 10, "Pruner"),
    Shrub("Hemerocallis", "Daylily", "1m - 3m", "1m - 3m", "Yellow, Orange", "Temperate", 15, "Shears"),
    Shrub("Heteromeles", "Toyon", "1m - 3m", "1m - 3m", "White", "Temperate", 50, "Pruner"),
    Shrub("Heuchera", "Coral Bells", "0.5m - 2m", "0.5m - 2m", "White, Pink", "Temperate", 15, "Shears"),
    Shrub("Hibbertia", "Hibbertia", "1m - 3m", "1m - 3m", "Yellow", "Temperate", 15, "Pruner"),
    Shrub("Hibiscus", "Hibiscus", "1m - 3m", "1m - 3m", "Red, Pink, Yellow, White", "Tropical", 15, "Shears"),
    Shrub("Holodiscus", "Ocean-spray", "1m - 3m", "1m - 3m", "White", "Temperate", 30, "Pruner"),
    Shrub("Hoya", "Hoya", "1m - 3m", "1m - 3m", "Pink", "Tropical", 30, "Shears"),
    Shrub("Hudsonia", "Golden Heather", "0.5m - 1m", "0.5m - 1m", "Yellow", "Temperate", 10, "Pruner"),
    Shrub("Hydrangea", "Hydrangea", "1m - 3m", "1m - 3m", "Pink, Blue, White", "Temperate", 20, "Shears"),
    Shrub("Hypericum", "St. John's Wort", "1m - 3m", "1m - 3m", "Yellow", "Temperate", 15, "Pruner"),
    Shrub("Ilex", "Holly", "1m - 3m", "1m - 3m", "Red, Green", "Temperate", 50, "Shears"),
    Shrub("Indigofera", "Indigofera", "0.5m - 1m", "0.5m - 1m", "Pink", "Temperate", 15, "Pruner"),
    Shrub("Itea", "Sweet Spire", "1m - 3m", "1m - 3m", "White", "Temperate", 20, "Shears"),
    Shrub("Jacaranda", "Jacaranda", "3m - 5m", "3m - 5m", "Purple", "Tropical", 50, "Pruner"),
    Shrub("Jasminum", "Jasmine", "1m - 3m", "1m - 3m", "White, Yellow", "Temperate", 30, "Shears"),
    Shrub("Juniperus", "Juniper", "1m - 3m", "1m - 3m", "Green, Blue", "Temperate", 50, "Pruner"),
    Shrub("Kalmia", "Mountain-laurel", "1m - 3m", "1m - 3m", "White, Pink", "Temperate", 40, "Shears"),
    Shrub("Kerria", "Japanese Rose", "1m - 3m", "1m - 3m", "Yellow", "Temperate", 20, "Pruner"),
    Shrub("Knautia", "Knautia", "1m - 3m", "1m - 3m", "Purple", "Temperate", 20, "Shears"),
    Shrub("Kolkwitzia", "Beautybush", "1m - 3m", "1m - 3m", "Pink", "Temperate", 30, "Pruner"),
    Shrub("Laburnum", "Laburnum", "1m - 3m", "1m - 3m", "Yellow", "Temperate", 50, "Shears"),
    Shrub("Lantana", "Lantana", "0.5m - 1m", "0.5m - 1m", "Pink, Yellow, Orange", "Tropical", 10, "Pruner"),
    Shrub("Larix", "Larch", "1m - 3m", "1m - 3m", "Green", "Temperate", 50, "Shears"),
    Shrub("Lavandula", "Lavender", "0.5m - 1m", "0.5m - 1m", "Purple, White", "Arid, Temperate", 15, "Pruner"),
    Shrub("Leptospermum", "Leptospermum", "1m - 3m", "1m - 3m", "White, Pink, Red", "Temperate", 30, "Shears"),
    Shrub("Lespedeza", "Lespedeza", "1m - 3m", "1m - 3m", "Pink, White", "Temperate", 20, "Pruner"),
    Shrub("Leucothoe", "Leucothoe", "1m - 3m", "1m - 3m", "White", "Temperate", 25, "Shears"),
    Shrub("Leycesteria", "Leycesteria", "1m - 3m", "1m - 3m", "White, Purple", "Temperate", 10, "Pruner"),
    Shrub("Ligustrum", "Privet", "1m - 3m", "1m - 3m", "White", "Temperate", 50, "Shears"),
    Shrub("Lilium", "Lily", "1m - 3m", "1m - 3m", "Yellow, Orange, Pink, White", "Temperate", 10, "Pruner"),
    Shrub("Linnaea", "Twinflower", "1m - 3m", "1m - 3m", "Pink", "Temperate", 15, "Shears"),
    Shrub("Liquidambar", "Sweetgum", "10m - 20m", "10m - 20m", "Green", "Temperate", 50, "Shears"),
    Shrub("Liriodendron", "Tulip tree", "15m - 30m", "15m - 30m", "Yellow, Green", "Temperate", 50, "Pruner"),
    Shrub("Lonicera", "Honeysuckle", "1m - 3m", "1m - 3m", "White, Yellow, Pink", "Temperate", 20, "Shears"),
    Shrub("Magnolia", "Magnolia", "5m - 15m", "5m - 15m", "White, Pink, Purple", "Temperate", 50, "Pruner"),
    Shrub("Malus", "Apple", "2m - 10m", "2m - 10m", "White, Pink", "Temperate", 50, "Shears"),
    Shrub("Mespilus", "Medlar", "5m - 8m", "5m - 8m", "White", "Temperate", 50, "Pruner"),
    Shrub("Nandina", "Heavenly Bamboo", "0.5m - 2m", "0.5m - 2m", "White, Pink", "Temperate", 20, "Shears"),
    Shrub("Nerium", "Oleander", "1m - 5m", "1m - 5m", "Pink, Red, White", "Temperate", 20, "Pruner"),
    Shrub("Oenothera", "Evening Primrose", "0.5m - 1m", "0.5m - 1m", "Yellow, Pink", "Temperate", 10, "Shears"),
    Shrub("Osmanthus", "Osmanthus", "2m - 10m", "2m - 10m", "White", "Temperate", 50, "Pruner"),
    Shrub("Paeonia", "Peony", "0.5m - 1.5m", "0.5m - 1.5m", "White, Pink, Red", "Temperate", 50, "Shears"),
    Shrub("Philadelphus", "Mock-orange", "1m - 3m", "1m - 3m", "White", "Temperate", 50, "Pruner"),
    Shrub("Pieris", "Pieris", "1m - 3m", "1m - 3m", "White, Pink", "Temperate", 30, "Shears"),
    Shrub("Plumbago", "Leadwort", "0.3m - 0.6m", "0.3m - 0.6m", "Blue", "Temperate", 10, "Pruner"),
    Shrub("Polygala", "Polygala", "0.5m - 1.5m", "0.5m - 1.5m", "Purple", "Temperate", 20, "Shears"),
    Shrub("Potentilla", "Potentilla", "0.5m - 1m", "0.5m - 1m", "Yellow, White", "Temperate", 20, "Pruner"),
    Shrub("Prunus", "Cherry", "2m - 10m", "2m - 10m", "White, Pink", "Temperate", 50, "Shears"),
    Shrub("Pseudotsuga", "Douglas-fir", "50m - 80m", "50m - 80m", "Green", "Temperate", 50, "Pruner"),
    Shrub("Ptelea", "Hop tree", "3m - 10m", "3m - 10m", "Green", "Temperate", 50, "Shears"),
    Shrub("Punica", "Pomegranate", "1m - 5m", "1m - 5m", "Red", "Temperate", 20, "Pruner"),
    Shrub("Quercus", "Oak", "10m - 30m", "10m - 30m", "Green", "Temperate", 50, "Shears"),
    Shrub("Rhododendron", "Rhododendron", "1m - 5m", "1m - 5m", "Purple, Pink, White", "Temperate", 50, "Pruner"),
    Shrub("Rhus", "Sumac", "1m - 5m", "1m - 5m", "Yellow, Red", "Temperate", 50, "Shears"),
    Shrub("Ribes", "Currant", "0.5m - 1.5m", "0.5m - 1.5m", "White, Pink, Red, Yellow", "Temperate", 20, "Pruner"),
    Shrub("Robinia", "Black Locust", "10m - 25m", "10m - 25m", "White, Pink", "Temperate", 50, "Shears"),
    Shrub("Rosa", "Rose", "0.5m - 3m", "0.5m - 3m", "White, Pink, Red, Yellow", "Temperate", 20, "Pruner"),
    Shrub("Rubus", "Blackberry", "0.5m - 3m", "0.5m - 3m", "White, Pink", "Temperate", 20, "Shears"),
    Shrub("Salix", "Willow", "1m - 25m", "1m - 25m", "Green", "Temperate", 50, "Pruner"),
    Shrub("Sambucus", "Elder", "2m - 6m", "2m - 6m", "White", "Temperate", 20, "Shears"),
    Shrub("Skimmia", "Skimmia", "0.5m - 1m", "0.5m - 1m", "White, Pink", "Temperate", 30, "Pruner"),
    Shrub("Sorbaria", "False spirea", "1m - 3m", "1m - 3m", "White", "Temperate", 20, "Shears"),
    Shrub("Spartium", "Spanish Broom", "2m - 4m", "2m - 4m", "Yellow", "Temperate", 20, "Pruner"),
    Shrub("Spiraea", "Spiraea", "0.5m - 2m", "0.5m - 2m", "White, Pink", "Temperate", 20, "Shears"),
    Shrub("Stephanandra", "Stephanandra", "1m - 2m", "1m - 2m", "Green", "Temperate", 30, "Pruner"),
    Shrub("Stewartia", "Stewartia", "2m - 8m", "2m - 8m", "White", "Temperate", 50, "Shears"),
    Shrub("Styrax", "Styrax", "2m - 12m", "2m - 12m", "White", "Temperate", 50, "Pruner"),
    Shrub("Symphoricarpos", "Snowberry", "0.5m - 2m", "0.5m - 2m", "White, Pink", "Temperate", 20, "Shears"),
    Shrub("Syringa", "Lilac", "2m - 10m", "2m - 10m", "Purple, White, Pink", "Temperate", 20, "Pruner"),
    Shrub("Tamarix", "Tamarix", "1m - 10m", "1m - 10m", "Pink, White", "Arid", 20, "Shears"),
    Shrub("Taxus", "Yew", "1m - 20m", "1m - 20m", "Green", "Temperate", 50, "Pruner"),
    Shrub("Thuja", "Arborvitae", "3m - 20m", "3m - 20m", "Green", "Temperate", 50, "Shears"),
    Shrub("Tibouchina", "Glory Bush", "1m - 4m", "1m - 4m", "Purple, Pink", "Tropical", 20, "Pruner"),
    Shrub("Tilia", "Linden", "20m - 40m", "20m - 40m", "Yellow, White", "Temperate", 50, "Shears"),
    Shrub("Trochodendron", "Wheel Tree", "4m - 15m", "4m - 15m", "Green", "Temperate", 50, "Pruner"),
    Shrub("Tsuga", "Hemlock", "15m - 60m", "15m - 60m", "Green", "Temperate", 50, "Shears"),
    Shrub("Vaccinium", "Blueberry", "0.5m - 3m", "0.5m - 3m", "White, Pink", "Temperate", 15, "Pruner"),
    Shrub("Viburnum", "Viburnum", "1m - 5m", "1m - 5m", "White, Pink", "Temperate", 30, "Shears"),
    Shrub("Weigela", "Weigela", "1m - 3m", "1m - 3m", "Pink, Red, White", "Temperate", 20, "Pruner"),
    Shrub("Wisteria", "Wisteria", "5m - 10m", "5m - 10m", "Purple, White, Pink", "Temperate", 15, "Shears"),
    Shrub("Yucca", "Yucca", "0.5m - 3m", "0.5m - 3m", "White", "Arid", 30, "Pruner"),
    Shrub("Zanthoxylum", "Prickly Ash", "1m - 15m", "1m - 15m", "Green", "Temperate", 20, "Shears"),
    Shrub("Zelkova", "Zelkova", "15m - 30m", "15m - 30m", "Green", "Temperate", 50, "Pruner"),
    Shrub("Ziziphus", "Jujube", "2m - 10m", "2m - 10m", "Yellow, Green", "Tropical", 15, "Shears"),
]